name: Blazor wasm

on:
  pull_request:
    branches: [ main ]

jobs:
  deploy-to-github-pages:
    runs-on: ubuntu-latest

    steps:
    - name: 🛒 Checkout
      uses: actions/checkout@v4

    - name: ✨ Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: 📦 Publish
      run: |
        cd src/AquaNotes
        dotnet publish -c Release -o publish

#   - name: 🚀 Deploy to GitHub Pages
#     uses: peaceiris/actions-gh-pages@v4
#     with:
#       github_token: ${{ secrets.GITHUB_TOKEN }}
#       publish_dir: src/AquaNotes/publish/wwwroot
#       force_orphan: true
